#!/usr/bin/env python3
"""
update_dashboard.py (v2)
─────────────────────────────────────────────────
Reads données_phd.xlsx and generates _data/collecte.yml for Jekyll.
Also updates the old dashboard.html for backward compatibility.
Usage:  python3 update_dashboard.py
─────────────────────────────────────────────────
"""

import os
import sys
from datetime import datetime, date

# ── Dependency check ──
try:
    import openpyxl
except ImportError:
    print("⚠️  openpyxl manquant. Installation en cours…")
    os.system(f"{sys.executable} -m pip install openpyxl --quiet")
    import openpyxl

# ── Paths ──
SCRIPT_DIR   = os.path.dirname(os.path.abspath(__file__))
EXCEL_FILE   = os.path.join(SCRIPT_DIR, "données_phd.xlsx")
YAML_OUTPUT  = os.path.join(SCRIPT_DIR, "_data", "collecte.yml")

# ── Section metadata ──
SECTIONS = {
    "Biologie":         {"color": "#2d8a4e", "icon": "🔬"},
    "Biomécanique":     {"color": "#e07b2a", "icon": "⚙️"},
    "Données Humaines": {"color": "#c0392b", "icon": "🧑‍⚕️"},
}

# ── Read Excel ──
def read_data(path):
    wb = openpyxl.load_workbook(path, data_only=True)
    ws = wb.active
    rows = []
    for row in ws.iter_rows(min_row=2, values_only=True):
        if not row[0] or str(row[0]).startswith("ℹ️"):
            continue
        partie, sous, statut, pct, deadline, notes = (
            str(row[0]).strip(),
            str(row[1]).strip(),
            str(row[2] or "Non démarré").strip(),
            int(row[3] or 0),
            row[4],
            str(row[5] or "").strip(),
        )
        dl_str = ""
        if deadline:
            d = deadline.date() if isinstance(deadline, datetime) else deadline
            dl_str = d.strftime("%d/%m/%Y")

        rows.append({
            "partie": partie,
            "sous": sous,
            "statut": statut,
            "pct": max(0, min(100, pct)),
            "deadline": dl_str,
            "notes": notes,
        })
    return rows

# ── Build YAML ──
def build_yaml(rows):
    sections = {}
    for r in rows:
        p = r["partie"]
        if p not in sections:
            sections[p] = []
        sections[p].append(r)

    now = datetime.now().strftime("%d/%m/%Y à %H:%M")

    lines = [
        "# Auto-generated by update_dashboard.py — do not edit manually",
        f'# Run: python3 update_dashboard.py to refresh from données_phd.xlsx',
        "",
        f'updated: "{now}"',
        "",
        "sections:",
    ]

    for partie, items in sections.items():
        meta = SECTIONS.get(partie, {"color": "#555", "icon": "📋"})
        lines.append(f'  - name: "{partie}"')
        lines.append(f'    icon: "{meta["icon"]}"')
        lines.append(f'    color: "{meta["color"]}"')
        lines.append(f'    items:')
        for item in items:
            # Escape quotes in strings
            name = item["sous"].replace('"', '\\"')
            notes = item["notes"].replace('"', '\\"')
            lines.append(f'      - name: "{name}"')
            lines.append(f'        status: "{item["statut"]}"')
            lines.append(f'        progress: {item["pct"]}')
            lines.append(f'        deadline: "{item["deadline"]}"')
            lines.append(f'        notes: "{notes}"')
            lines.append(f'')

    return "\n".join(lines)

# ── Main ──
def main():
    if not os.path.exists(EXCEL_FILE):
        print(f"❌  Fichier introuvable : {EXCEL_FILE}")
        print(f"    Cherché dans : {SCRIPT_DIR}")
        sys.exit(1)

    print(f"📖  Lecture de {os.path.basename(EXCEL_FILE)}…")
    rows = read_data(EXCEL_FILE)

    # Generate YAML for Jekyll
    yaml_content = build_yaml(rows)

    os.makedirs(os.path.dirname(YAML_OUTPUT), exist_ok=True)
    with open(YAML_OUTPUT, "w", encoding="utf-8") as f:
        f.write(yaml_content)

    # Summary
    total = len(rows)
    done = sum(1 for r in rows if r["statut"] == "Terminé")
    avg = round(sum(r["pct"] for r in rows) / total) if total else 0

    print(f"✅  YAML généré : {YAML_OUTPUT}")
    print(f"    → {total} sous-parties, {done} terminées, {avg}% global")
    print(f"    → Fais un `git add _data/collecte.yml && git commit && git push`")
    print(f"    → GitHub Pages régénère le site automatiquement.")

if __name__ == "__main__":
    main()
